### ISSUE TITLE
Dump github context

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/greenfield-template#315]
Show the contents of the github context.  Informative, allows us to know what's in that object and create more inteligent Actions.

Note: bad copy and paste!  Clean up!

This is a job:
```
  view-context:
    name: View GitHub Context
    runs-on: ubuntu-latest
    steps:
      - name: Echo GitHub context
        run: echo '${{ toJSON(github) }}'
```

Please work at least a little bit of this into our documentation.  Good to know!
