### ISSUE TITLE
Reduce GitHub spam

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/greenfield-template#484]
We could use ChatOps or silence output for draft PRs.

Run if PR out of draft:
```
on:
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]
```
and
```
if: github.event.pull_request.draft == false
```

ChatOps (one Action of many):
https://github.com/peter-evans/slash-command-dispatch
